services:
  rproxy:
    networks:
      default:
        aliases:
          - idp.aimerzarashi.com
          - web.aimerzarashi.com
    image: traefik:v3.0
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./rproxy:/etc/traefik:ro
      - ./logs:/etc/logs
    environment:
      - TZ=Asia/Tokyo
    command:
      - --accesslog.fields.names.StartUTC=drop
      - --providers.docker
  whoami:
    image: traefik/whoami
  web:
    image: node:20-alpine3.18
    ports:
      - 3000:3000
    depends_on:
      - idp
    volumes:
      - ./web:/app
    tty: true
    working_dir: /app
    command:
      - "sh"
      - "-c"
      - |
        npm install;
        npm run dev;
  idp:
    image: keycloak/keycloak:25.0
    environment:
      KEYCLOAK_ADMIN: user
      KEYCLOAK_ADMIN_PASSWORD: bitnami
      KC_DB: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_HOST: db
      KC_DB_URL_DATABASE: bitnami_keycloak
      KC_DB_PASSWORD: password
      KC_DB_USERNAME: bn_keycloak
      KC_HOSTNAME_URL: "https://idp.aimerzarashi.com"
      KC_HOSTNAME_ADMIN_URL: "https://idp.aimerzarashi.com"
      KC_HOSTNAME_STRICT: false
      KC_PROXY_HEADERS: "xforwarded"
      KC_HTTPS_CLIENT_AUTH: request
      KC_HTTPS_KEY_STORE_FILE: /opt/keycloak/conf/truststores/keystore.p12
      KC_HTTPS_KEY_STORE_PASSWORD: 2345
      KC_HTTPS_TRUST_STORE_FILE: /opt/keycloak/conf/truststores/truststore.p12
      KC_HTTPS_TRUST_STORE_PASSWORD: 4567
      KC_SPI_TRUSTSTORE_FILE_FILE: /opt/keycloak/conf/truststores/truststore.p12
      KC_SPI_TRUSTSTORE_FILE_PASSWORD: 4567
    command:
      # - "start-dev"
      - "start"
    volumes:
      - ./idp/certs:/opt/keycloak/conf/truststores
    # image: bitnami/keycloak:24
    # environment:
    #   KEYCLOAK_ADMIN_USER: user
    #   KEYCLOAK_ADMIN_PASSWORD: bitnami
    #   KEYCLOAK_DATABASE_HOST: db
    #   KEYCLOAK_DATABASE_PORT: 5432
    #   KEYCLOAK_DATABASE_NAME: bitnami_keycloak
    #   KEYCLOAK_DATABASE_USER: bn_keycloak
    #   KEYCLOAK_DATABASE_PASSWORD: password
    #   KC_HOSTNAME_URL: "https://idp.aimerzarashi.com"
    #   KC_HOSTNAME_ADMIN_URL: "https://idp.aimerzarashi.com"
    # KEYCLOAK_PROXY: edge
    # KEYCLOAK_PRODUCTION: true
    # KEYCLOAK_ENABLE_HTTPS: true
    # KEYCLOAK_HTTPS_USE_PEM: true
    # KEYCLOAK_HTTPS_CERTIFICATE_FILE: /opt/bitnami/keycloak/certs/server.pem
    # KEYCLOAK_HTTPS_CERTIFICATE_KEY_FILE: /opt/bitnami/keycloak/certs/server.key
    # KEYCLOAK_PROXY: reencrypt
    # KEYCLOAK_PRODUCTION: true
    # KEYCLOAK_ENABLE_HTTPS: true
    # KEYCLOAK_HTTPS_KEY_STORE_FILE: /opt/bitnami/keycloak/certs/keystore.jks
    # KEYCLOAK_HTTPS_KEY_STORE_PASSWORD: 123456
    # KEYCLOAK_HTTPS_TRUST_STORE_FILE: /opt/bitnami/keycloak/certs/truststore.jks
    # KEYCLOAK_HTTPS_TRUST_STORE_PASSWORD: 234567
    # KEYCLOAK_SPI_TRUSTSTORE_FILE: /opt/bitnami/keycloak/certs/truststore.jks
    # KEYCLOAK_SPI_TRUSTSTORE_PASSWORD: 234567
    # volumes:
    #   - ./idp/certs:/opt/bitnami/keycloak/certs
    depends_on:
      - db
      - smtp
  db:
    container_name: db
    image: postgres:16.3
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: bn_keycloak
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bitnami_keycloak
    volumes:
      - ./db/data:/var/lib/postgresql/data
  smtp:
    image: mailhog/mailhog
    ports:
      - 1025:1025
